/*room_type*/
DROP TABLE ROOM_TYPE CASCADE CONSTRAINTS;
CREATE TABLE ROOM_TYPE (
   TYPE_ID   NUMBER(4)      NOT NULL,
   TYPE_NAME   VARCHAR2(50)      NOT NULL
);

/*department*/
DROP TABLE department CASCADE CONSTRAINTS;
CREATE TABLE department (
   DEPT_IDEN   varchar2(10)      NOT NULL,
   DEPT_NAME   varchar2(200)      NOT NULL
);

/*sms*/
DROP TABLE SMS CASCADE CONSTRAINTS;
CREATE TABLE SMS (
   SMS_ID   NUMBER(20)      NOT NULL,
   RESERVATION_ID   NUMBER(20)      NOT NULL,
   SMS_CONTENT   VARCHAR2(500)      NULL,
   SENT_TIME   TIMESTAMP      NULL,
   SENT_STATUS   VARCHAR2(10)      NULL
);

/*Reservation*/
DROP TABLE RESERVATION CASCADE CONSTRAINTS;
CREATE TABLE RESERVATION (
   RESV_ID   NUMBER(20)      NOT NULL,
   ROOM_ID   NUMBER(4)      NOT NULL,
   USER_NUM   NUMBER(20)      NOT NULL,
   NON_MEM_ID   NUMBER(5)      NOT NULL,
   PAYMENT_ID   NUMBER(20)      NOT NULL,
   CHECKIN_DATE   DATE      NOT NULL,
   CHECKOUT_DATE   DATE      NOT NULL,
   NUM_GUESTS   NUMBER(2)      NOT NULL,
   STATUS   VARCHAR2(20)      NOT NULL,
   RESV_REG_DATE   DATE   DEFAULT sysdate   NOT NULL,
   REQUEST_MSG   VARCHAR2(1000)      NULL
);

/*position*/
DROP TABLE position CASCADE CONSTRAINTS;
CREATE TABLE position (
   POSITION_IDENTIFIED_CODE   char(1)      NOT NULL,
   POSITION_NAME   varchar2(20)      NOT NULL,
   POSITION_AUTHORITY_LEVEL   number(3)      NOT NULL
);

/*view_type*/
DROP TABLE VIEW_TYPE CASCADE CONSTRAINTS;
CREATE TABLE VIEW_TYPE (
   VIEW_ID   NUMBER(1)      NOT NULL,
   VIEW_NAME   VARCHAR2(50)      NOT NULL
);

/*file*/
DROP TABLE FILE_PATH CASCADE CONSTRAINTS;
CREATE TABLE FILE_PATH (
   PROPERTY_ID   VARCHAR2(255)      NOT NULL,
   PATH   VARCHAR2(255)      NOT NULL,
   TARGET_TYPE   VARCHAR2(100)      NOT NULL,
   TARGET_NUMBER   VARCHAR2(100)      NOT NULL,
   IMG_NAME   VARCHAR2(255)      NOT NULL
);

/*chat_message*/
DROP TABLE CHAT_MESSAGE CASCADE CONSTRAINTS;
CREATE TABLE CHAT_MESSAGE (
   MESSAGE_ID   int      NOT NULL,
   ROOM_ID   int      NOT NULL,
   STAFF_ID   varchar2(15)      NOT NULL,
   LOG_IDEN   VARCHAR2(30)      NOT NULL,
   CONTENT   varchar2(255)      NULL,
   SEND_TIME   TIMESTAMP      NOT NULL,
   IS_READ   char(1)      NULL
);

/*staff*/
DROP TABLE STAFF CASCADE CONSTRAINTS;
CREATE TABLE STAFF (
   STAFF_ID   varchar2(15)      NOT NULL,
   POSITION_IDENTIFIED_CODE   char(1)      NOT NULL,
   DEPT_IDEN   varchar2(10)      NOT NULL,
   LOG_IDEN   VARCHAR2(30)      NOT NULL,
   STAFF_PASS   varchar2(256)      NOT NULL,
   STAFF_NAME   varchar2(20)      NOT NULL,
   STAFF_STATUS   varchar2(10)      NOT NULL,
   STAFF_EMAIL   varchar2(200)      NOT NULL,
   DATE_OF_EMPLOYMENT   varchar2(20)      NOT NULL,
   RETIRE_DATE   varchar2(10)      NULL
);

/*room*/
DROP TABLE ROOM CASCADE CONSTRAINTS;
CREATE TABLE ROOM (
   ROOM_ID   NUMBER(4)      NOT NULL,
   BED_ID   NUMBER(1)      NOT NULL,
   TYPE_ID   NUMBER(4)      NOT NULL,
   VIEW_ID   NUMBER(1)      NOT NULL,
   CAPACITY   NUMBER(2)      NOT NULL,
   PRICE_PER_NIGHT   NUMBER(10,2)      NOT NULL,
   AREA_SQM   NUMBER(5,2)      NOT NULL,
   ROOM_FLOOR   NUMBER(3)      NOT NULL,
   DESCRIPTION   CLOB      NOT NULL
);

/*log_record*/
DROP TABLE LOG_RECORD CASCADE CONSTRAINTS;
CREATE TABLE LOG_RECORD (
   LOG_IDEN   VARCHAR2(30)      NOT NULL,
   LOG_FILE_NAME   VARCHAR2(30)      NOT NULL
);

/*bed_type*/
DROP TABLE BED_TYPE CASCADE CONSTRAINTS;
CREATE TABLE BED_TYPE (
   BED_ID   NUMBER(1)      NOT NULL,
   BED_NAME   VARCHAR2(50)      NOT NULL
);

/*rep_menu*/
DROP TABLE REP_MENU CASCADE CONSTRAINTS;
CREATE TABLE REP_MENU (
   MENU_ID   NUMBER(5)      NOT NULL,
   DINING_ID   NUMBER(5)      NOT NULL,
   MENU_NAME   VARCHAR2(200)      NOT NULL,
   DESCRIPTION   VARCHAR2(200)      NOT NULL,
   PRICE   NUMBER(10)      NOT NULL
);

/*faq*/
DROP TABLE FAQ CASCADE CONSTRAINTS;
CREATE TABLE FAQ (
   FAQ_NUM   NUMBER(10)      NOT NULL,
   FAQ_TITLE   VARCHAR2(255)      NULL,
   FAQ_CONTENT   VARCHAR2(255)      NULL,
   FAQ_DATE   DATE      NULL
);

/*dinning_oper_time*/
DROP TABLE DINING_OPER_TIME CASCADE CONSTRAINTS;
CREATE TABLE DINING_OPER_TIME (
   HOUR_ID   NUMBER(5)      NOT NULL,
   DINING_ID   NUMBER(5)      NOT NULL,
   HOUR_TYPE   VARCHAR2(10)      NULL,
   START_TIME   DATE      NULL,
   END_TIME   DATE      NULL
);

/*non_member*/
DROP TABLE NON_MEMBER CASCADE CONSTRAINTS;
CREATE TABLE NON_MEMBER (
   NON_MEM_ID   NUMBER(5)      NOT NULL,
   NON_MEM_NAME   VARCHAR2(100)      NOT NULL,
   NON_MEM_TEL   VARCHAR2(20)      NOT NULL,
   NON_MEM_REG_DATE   DATE   DEFAULT sysdate   NOT NULL,
   NON_MEM_EMAIL   VARCHAR2(100)      NOT NULL
);

/*payment*/
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
CREATE TABLE PAYMENT (
   PAYMENT_ID   NUMBER(20)      NOT NULL,
   RESERVATION_ID   VARCHAR2(20)      NOT NULL,
   PAYMENT_PRICE   NUMBER(10)      NULL,
   PAYMENT_TYPE   VARCHAR2(10)      NULL,
   PAYMENT_STATUS   VARCHAR2(10)      NULL,
   PAYMENT_TIME   TIMESTAMP      NULL
);

/*inquiry*/
DROP TABLE INQUIRY CASCADE CONSTRAINTS;
CREATE TABLE INQUIRY (
   INQUIRY_NUM   NUMBER(10)      NOT NULL,
   USER_NUM   NUMBER(20)      NOT NULL,
   INQUIRY_CONTENT   CLOB      NULL,
   INQUIRY_CATEGORY   CHAR(1)      NULL,
   INQUIRY_TITLE   VARCHAR2(255)      NULL,
   INQUIRY_ANSWER   CLOB      NULL,
   INQUIRY_STATUS   CHAR(1)      NULL,
   INQUIRY_REQ_DATE   DATE      NULL,
   INQUIRY_ANSWER_DATE   DATE      NULL
);

/*dinning*/
DROP TABLE DINING CASCADE CONSTRAINTS;
CREATE TABLE DINING (
   DINING_ID   NUMBER(5)      NOT NULL,
   DINING_NAME   VARCHAR2(200)      NULL,
   TYPE   VARCHAR(255)      NOT NULL,
   LOCATION   VARCHAR(255)      NOT NULL,
   PHONE_NUMBER   VARCHAR(255)      NOT NULL,
   MANAGER_NAME   VARCHAR2(15)      NOT NULL,
   DETAIL_CONTENT   CLOB      NULL
);

/*permission*/
DROP TABLE permission CASCADE CONSTRAINTS;
CREATE TABLE permission (
   PERMISSION_ID_CODE   varchar2(20)      NOT NULL,
   PERMISSION_TYPE   varchar2(100)      NOT NULL
);

/*room_feature*/
DROP TABLE ROOM_FEATURE CASCADE CONSTRAINTS;
CREATE TABLE ROOM_FEATURE (
   ROOM_ID   NUMBER(4)      NOT NULL,
   BREAKFAST   NUMBER(2)      NOT NULL,
   BATHTUB   CHAR(1)      NOT NULL
);

/*dinning_reservation*/
DROP TABLE DINING_RESERVATION CASCADE CONSTRAINTS;
CREATE TABLE DINING_RESERVATION (
   RESERVATION_ID   NUMBER(20)      NOT NULL,
   DINING_ID   NUMBER(5)      NOT NULL,
   USER_NUM   NUMBER(20)      NOT NULL,
   PAYMENT_ID   NUMBER(20)      NOT NULL,
   NON_MEM_ID   NUMBER(5)      NOT NULL,
   RESERVATION_NAME   VARCHAR2(10)      NULL,
   RESERVATION_DATE   DATE      NULL,
   RESERVATION_TIME   TIMESTAMP      NULL,
   RESERVATION_COUNT   NUMBER(10)      NULL,
   RESERVATION_REQUEST   VARCHAR2(500)      NULL,
   RESERVATION_TELL   VARCHAR2(20)      NULL,
   RESERVATION_STATUS   VARCHAR2(10)      NULL
);

/*staff_permission*/
DROP TABLE staff_permission CASCADE CONSTRAINTS;
CREATE TABLE staff_permission (
   PERMISSION_ID__CODE   varchar2(20)      NOT NULL,
   STAFF_ID   varchar2(15)      NOT NULL,
   LOG_IDEN   VARCHAR2(30)      NOT NULL
);

/*mimir_user*/
DROP TABLE MIMIR_USER CASCADE CONSTRAINTS;
CREATE TABLE MIMIR_USER (
   USER_NUM   NUMBER(20)      NOT NULL,
   LOGIN_TYPE   VARCHAR2(10)      NOT NULL,
   OAUTH_ID   VARCHAR2(100)      NULL,
   EMAIL_ID   VARCHAR2(100)      NULL,
   PASSWORD   VARCHAR2(255)      NULL,
   EMAIL_AUTH   CHAR(1)      NULL,
   EMAIL_REFRESH_TOKEN   VARCHAR2(100)      NULL,
   EMAIL_AUTH_EXPIRE   TIMESTAMP      NULL,
   USER_NAME   VARCHAR2(50)      NULL,
   BIRTH_DATE   DATE      NULL,
   GENDER   VARCHAR2(1)      NULL,
   TEL   VARCHAR2(13)      NULL,
   LAST_LOGIN_TIME   TIMESTAMP      NULL,
   SOCIAL_REFRESH_TOKEN   VARCHAR2(100)      NULL,
   SOCIAL_TOKEN_EXPIRE   TIMESTAMP      NULL,
   REG_TIME   TIMESTAMP      NOT NULL,
   UPDATE_TIME   TIMESTAMP      NULL,
   QUIT_TIME   TIMESTAMP      NULL,
   USE_YN   VARCHAR2(1)   DEFAULT 'N'   NULL
);

/*chat_room*/
DROP TABLE CHAT_ROOM CASCADE CONSTRAINTS;
CREATE TABLE CHAT_ROOM (
   ROOM_ID   int      NOT NULL,
   USER_NUM   NUMBER(20)      NOT NULL,
   STAFF_ID   varchar2(15)      NOT NULL,
   LOG_IDEN   VARCHAR2(30)      NOT NULL,
   CHAT_TYPE   char(1)      NOT NULL
);
