DROP TABLE ROOM_TYPE CASCADE CONSTRAINTS;

CREATE TABLE ROOM_TYPE (
	TYPE_ID	NUMBER(4)		NOT NULL,
	TYPE_NAME	VARCHAR2(50)		NOT NULL
);

DROP TABLE department CASCADE CONSTRAINTS;

CREATE TABLE department (
	DEPT_IDEN	varchar2(10)		NOT NULL,
	DEPT_NAME	varchar2(200)		NOT NULL
);

DROP TABLE SMS CASCADE CONSTRAINTS;

CREATE TABLE SMS (
	SMS_ID	NUMBER(20)		NOT NULL,
	RESERVATION_ID	NUMBER(20)		NOT NULL,
	SMS_CONTENT	VARCHAR2(500)		NULL,
	SENT_TIME	TIMESTAMP		NULL,
	SENT_STATUS	VARCHAR2(10)		NULL
);

DROP TABLE RESERVATION CASCADE CONSTRAINTS;

CREATE TABLE RESERVATION (
	RESV_ID	NUMBER(20)		NOT NULL,
	ROOM_ID	NUMBER(4)		NOT NULL,
	USER_NUM	NUMBER(20)		NULL,
	NON_MEM_ID	NUMBER(5)		NULL,
	PAYMENT_ID	NUMBER(20)		NOT NULL,
	CHECKIN_DATE	DATE		NOT NULL,
	CHECKOUT_DATE	DATE		NOT NULL,
	NUM_GUESTS	NUMBER(2)		NOT NULL,
	STATUS	VARCHAR2(20)		NOT NULL,
	RESV_REG_DATE	DATE	DEFAULT sysdate	NOT NULL,
	REQUEST_MSG	VARCHAR2(1000)		NULL
);


DROP TABLE position CASCADE CONSTRAINTS;

CREATE TABLE position (
	POSITION_IDENTIFIED_CODE	char(1)		NOT NULL,
	POSITION_NAME	varchar2(20)		NOT NULL,
	POSITION_AUTHORITY_LEVEL	number(3)		NOT NULL
);




DROP TABLE VIEW_TYPE CASCADE CONSTRAINTS;

CREATE TABLE VIEW_TYPE (
	VIEW_ID	NUMBER(1)		NOT NULL,
	VIEW_NAME	VARCHAR2(50)		NOT NULL
);

DROP TABLE FILE_PATH CASCADE CONSTRAINTS;

CREATE TABLE FILE_PATH (
	PROPERTY_ID	VARCHAR2(255) 	NOT NULL,
	PATH	VARCHAR2(255)		NOT NULL,
	TARGET_TYPE	VARCHAR2(100)		NOT NULL,
	TARGET_NUMBER	VARCHAR2(100)		NOT NULL,
	IMG_NAME	VARCHAR2(255)		NOT NULL
);

DROP TABLE CHAT_MESSAGE CASCADE CONSTRAINTS;

CREATE TABLE CHAT_MESSAGE (
	MESSAGE_ID	int		NOT NULL,
	ROOM_ID	int		NOT NULL,
	STAFF_ID	varchar2(15)		NOT NULL,
	DEPT_IDEN	varchar2(10)		NOT NULL,
	CONTENT	varchar2(255)		NULL,
	SEND_TIME	TIMESTAMP(5)		NOT NULL,
	IS_READ	char(1)		NULL
);

DROP TABLE STAFF CASCADE CONSTRAINTS;

CREATE TABLE STAFF (
	STAFF_ID	varchar2(15)		NOT NULL,
	POSITION_IDENTIFIED_CODE	char(1)		NOT NULL,
	DEPT_IDEN	varchar2(10)		NOT NULL,
	LOG_IDEN	VARCHAR2(30)		NOT NULL,
	STAFF_PASS	varchar2(256)		NOT NULL,
	STAFF_NAME	varchar2(20)		NOT NULL,
	STAFF_STATUS	varchar2(10)		NOT NULL,
	STAFF_EMAIL	varchar2(200)		NOT NULL,
	DATE_OF_EMPLOYMENT	varchar2(20)		NOT NULL,
	RETIRE_DATE	varchar2(10)		NULL
);




DROP TABLE ROOM CASCADE CONSTRAINTS;

CREATE TABLE ROOM (
	ROOM_ID	NUMBER(4)		NOT NULL,
	BED_ID	NUMBER(1)		NOT NULL,
	TYPE_ID	NUMBER(4)		NOT NULL,
	VIEW_ID	NUMBER(1)		NOT NULL,
	CAPACITY	NUMBER(2)		NOT NULL,
	PRICE_PER_NIGHT	NUMBER(10,2)		NOT NULL,
	AREA_SQM	NUMBER(5,2)		NOT NULL,
	ROOM_FLOOR	NUMBER(3)		NOT NULL,
	DESCRIPTION	CLOB		NOT NULL
);

DROP TABLE LOG_RECORD CASCADE CONSTRAINTS;

CREATE TABLE LOG_RECORD (
	LOG_IDEN	VARCHAR2(30)		NOT NULL,
	LOG_FILE_NAME	VARCHAR2(30)		NOT NULL
);



DROP TABLE BED_TYPE CASCADE CONSTRAINTS;

CREATE TABLE BED_TYPE (
	BED_ID	NUMBER(1)		NOT NULL,
	BED_NAME	VARCHAR2(50)		NOT NULL
);

DROP TABLE REP_MENU CASCADE CONSTRAINTS;

CREATE TABLE REP_MENU (
	MENU_ID	NUMBER(5)		NOT NULL,
	DINING_ID	NUMBER(5)		NOT NULL,
	MENU_NAME	VARCHAR2(200)		NOT NULL,
	DESCRIPTION	VARCHAR2(200)		NOT NULL,
	PRICE	NUMBER(10)		NOT NULL
);


DROP TABLE FAQ CASCADE CONSTRAINTS;

CREATE TABLE FAQ (
	FAQ_NUM	NUMBER(10)		NOT NULL,
	FAQ_TITLE	VARCHAR2(255)		NULL,
	FAQ_CONTENT	clob		NULL,
	FAQ_DATE	DATE		NULL
);

DROP TABLE DINING_OPER_TIME CASCADE CONSTRAINTS;

CREATE TABLE DINING_OPER_TIME (
	HOUR_ID	NUMBER(5)		NOT NULL,
	DINING_ID	NUMBER(5)		NOT NULL,
	HOUR_TYPE	VARCHAR2(10)		NULL,
	START_TIME	DATE		NULL,
	END_TIME	DATE		NULL
);


DROP TABLE NON_MEMBER CASCADE CONSTRAINTS;

CREATE TABLE NON_MEMBER (
	NON_MEM_ID	NUMBER(5)		NOT NULL,
	NON_MEM_NAME	VARCHAR2(100)		NOT NULL,
	NON_MEM_TEL	VARCHAR2(20)		NOT NULL,
	NON_MEM_REG_DATE	DATE	DEFAULT sysdate	NOT NULL,
	NON_MEM_EMAIL	VARCHAR2(100)		NOT NULL
);

DROP TABLE PAYMENT CASCADE CONSTRAINTS;

CREATE TABLE PAYMENT (
	PAYMENT_ID	NUMBER(20)		NOT NULL,
	RESERVATION_ID	VARCHAR2(20)		NOT NULL,
	PAYMENT_PRICE	NUMBER(10)		NULL,
	PAYMENT_TYPE	VARCHAR2(10)		NULL,
	PAYMENT_STATUS	VARCHAR2(10)		NULL,
	PAYMENT_TIME	TIMESTAMP		NULL
);

DROP TABLE DINING CASCADE CONSTRAINTS;

CREATE TABLE DINING (
	DINING_ID	NUMBER(5)		NOT NULL,
	DINING_NAME	VARCHAR2(200)		NULL,
	TYPE	VARCHAR(255)		NOT NULL,
	LOCATION	VARCHAR(255)		NOT NULL,
	PHONE_NUMBER	VARCHAR(255)		NOT NULL,
	MANAGER_NAME	VARCHAR2(15)		NOT NULL,
	DETAIL_CONTENT	CLOB		NULL
);







DROP TABLE permission CASCADE CONSTRAINTS;

CREATE TABLE permission (
	PERMISSION_ID_CODE	varchar2(20)		NOT NULL,
	PERMISSION_TYPE	varchar2(100)		NOT NULL
);



DROP TABLE ROOM_FEATURE CASCADE CONSTRAINTS;

CREATE TABLE ROOM_FEATURE (
	ROOM_ID	NUMBER(4)		NOT NULL,
	BREAKFAST	NUMBER(2)		NOT NULL,
	BATHTUB	CHAR(1)		NOT NULL
);

DROP TABLE DINING_RESERVATION CASCADE CONSTRAINTS;

CREATE TABLE DINING_RESERVATION (
	RESERVATION_ID	NUMBER(20)		NOT NULL,
	DINING_ID	NUMBER(5)		NOT NULL,
	USER_NUM	NUMBER(20)		NOT NULL,
	PAYMENT_ID	NUMBER(20)		NOT NULL,
	NON_MEM_ID	NUMBER(5)		NOT NULL,
	RESERVATION_NAME	VARCHAR2(10)		NULL,
	RESERVATION_DATE	DATE		NULL,
	RESERVATION_TIME	TIMESTAMP		NULL,
	RESERVATION_COUNT	NUMBER(10)		NULL,
	RESERVATION_REQUEST	VARCHAR2(500)		NULL,
	RESERVATION_TELL	VARCHAR2(20)		NULL,
	RESERVATION_STATUS	VARCHAR2(10)		NULL
);



DROP TABLE staff_permission CASCADE CONSTRAINTS;

CREATE TABLE staff_permission (
	PERMISSION_ID_CODE	varchar2(20)		NOT NULL,
	STAFF_ID	varchar2(15)		NOT NULL
);



DROP TABLE MIMIR_USER CASCADE CONSTRAINTS;

CREATE TABLE MIMIR_USER (
	USER_NUM	NUMBER(20)		NOT NULL,
	LOGIN_TYPE	VARCHAR2(10)		NOT NULL,
	OAUTH_ID	VARCHAR2(100)		NULL,
	EMAIL_ID	VARCHAR2(100)		NULL,
	PASSWORD	VARCHAR2(255)		NULL,
	EMAIL_AUTH	CHAR(1)		NULL,
	EMAIL_REFRESH_TOKEN	VARCHAR2(100)		NULL,
	EMAIL_AUTH_EXPIRE	TIMESTAMP		NULL,
	USER_NAME	VARCHAR2(50)		NULL,
	BIRTH_DATE	DATE		NULL,
	GENDER	VARCHAR2(1)		NULL,
	TEL	VARCHAR2(13)		NULL,
	LAST_LOGIN_TIME	TIMESTAMP		NULL,
	SOCIAL_REFRESH_TOKEN	VARCHAR2(100)		NULL,
	SOCIAL_TOKEN_EXPIRE	TIMESTAMP		NULL,
	REG_TIME	TIMESTAMP		NOT NULL,
	UPDATE_TIME	TIMESTAMP		NULL,
	QUIT_TIME	TIMESTAMP		NULL,
	USE_YN	VARCHAR2(1)	DEFAULT 'N'	NULL
);


DROP TABLE CHAT_ROOM CASCADE CONSTRAINTS;

CREATE TABLE CHAT_ROOM (
	ROOM_ID	int		NOT NULL,
	USER_NUM	NUMBER(20)		NOT NULL,
	STAFF_ID	varchar2(15)		NOT NULL,
	DEPT_IDEN	varchar2(10)		NOT NULL,
	CHAT_TYPE	char(1)		NOT NULL,
	Field	VARCHAR(255)		NULL
);


ALTER TABLE ROOM_TYPE ADD CONSTRAINT PK_ROOM_TYPE_TYPE_ID PRIMARY KEY (TYPE_ID);

ALTER TABLE department ADD CONSTRAINT PK_department_DEPT_IDEN PRIMARY KEY (DEPT_IDEN);

ALTER TABLE SMS ADD CONSTRAINT PK_SMS_SMS_ID PRIMARY KEY (SMS_ID);


ALTER TABLE RESERVATION ADD CONSTRAINT PK_RESERVATION_RESV_ID PRIMARY KEY (RESV_ID);


ALTER TABLE position ADD CONSTRAINT PK_position_POSITION_IDENTIFIED_CODE PRIMARY KEY (POSITION_IDENTIFIED_CODE);

ALTER TABLE VIEW_TYPE ADD CONSTRAINT PK_VIEW_TYPE_VIEW_ID PRIMARY KEY (VIEW_ID);

ALTER TABLE FILE_PATH ADD CONSTRAINT PK_FILE_PATH_PROPERTY_ID PRIMARY KEY (PROPERTY_ID);

ALTER TABLE CHAT_MESSAGE ADD CONSTRAINT PK_CHAT_MESSAGE_MESSAGE_ID PRIMARY KEY (MESSAGE_ID);


ALTER TABLE STAFF ADD CONSTRAINT PK_STAFF_STAFF_ID PRIMARY KEY (STAFF_ID);


ALTER TABLE ROOM ADD CONSTRAINT PK_ROOM_ROOM_ID PRIMARY KEY (ROOM_ID);


ALTER TABLE LOG_RECORD ADD CONSTRAINT PK_LOG_RECORD_LOG_IDEN PRIMARY KEY (LOG_IDEN);

ALTER TABLE BED_TYPE ADD CONSTRAINT PK_BED_TYPE_BED_ID PRIMARY KEY (BED_ID);

ALTER TABLE REP_MENU ADD CONSTRAINT PK_REP_MENU_MENU_ID PRIMARY KEY (MENU_ID);


ALTER TABLE FAQ ADD CONSTRAINT PK_FAQ_FAQ_NUM PRIMARY KEY (FAQ_NUM);

ALTER TABLE DINING_OPER_TIME ADD CONSTRAINT PK_DINING_OPER_TIME_HOUR_ID PRIMARY KEY (HOUR_ID);


ALTER TABLE NON_MEMBER ADD CONSTRAINT PK_NON_MEMBER_NON_MEM_ID PRIMARY KEY (NON_MEM_ID);

ALTER TABLE PAYMENT ADD CONSTRAINT PK_PAYMENT_PAYMENT_ID PRIMARY KEY (PAYMENT_ID);

ALTER TABLE DINING ADD CONSTRAINT PK_DINING_DINING_ID PRIMARY KEY (DINING_ID);

ALTER TABLE permission ADD CONSTRAINT PK_permission_PERMISSION_ID_CODE PRIMARY KEY (PERMISSION_ID_CODE);

ALTER TABLE ROOM_FEATURE ADD CONSTRAINT PK_ROOM_FEATURE_ROOM_ID PRIMARY KEY (ROOM_ID);

ALTER TABLE DINING_RESERVATION ADD CONSTRAINT PK_DINING_RESERVATION_RESERVATION_ID PRIMARY KEY (RESERVATION_ID);


ALTER TABLE MIMIR_USER ADD CONSTRAINT PK_MIMIR_USER_USER_NUM PRIMARY KEY (USER_NUM);

ALTER TABLE CHAT_ROOM ADD CONSTRAINT PK_CHAT_ROOM_ROOM_ID PRIMARY KEY (ROOM_ID);


ALTER TABLE SMS ADD CONSTRAINT FK_SMS_TO_DINING_RESERVATION_RESERVATION_ID FOREIGN KEY (
		RESERVATION_ID
)
REFERENCES DINING_RESERVATION (
		RESERVATION_ID
);

ALTER TABLE RESERVATION ADD CONSTRAINT FK_RESERVATION_TO_ROOM_ROOM_ID FOREIGN KEY (
		ROOM_ID
)
REFERENCES ROOM (
		ROOM_ID
);

ALTER TABLE RESERVATION ADD CONSTRAINT FK_RESERVATION_TO_MIMIR_USER_USER_NUM FOREIGN KEY (
		USER_NUM
)
REFERENCES MIMIR_USER (
		USER_NUM
);

ALTER TABLE RESERVATION ADD CONSTRAINT FK_RESERVATION_TO_NON_MEMBER_NON_MEM_ID FOREIGN KEY (
		NON_MEM_ID
)
REFERENCES NON_MEMBER (
		NON_MEM_ID
);

ALTER TABLE RESERVATION ADD CONSTRAINT FK_RESERVATION_TO_PAYMENT_PAYMENT_ID FOREIGN KEY (
		PAYMENT_ID
)
REFERENCES PAYMENT (
		PAYMENT_ID
);

ALTER TABLE CHAT_MESSAGE ADD CONSTRAINT FK_CHAT_MESSAGE_TO_CHAT_ROOM_ROOM_ID FOREIGN KEY (
		ROOM_ID
)
REFERENCES CHAT_ROOM (
		ROOM_ID
);

ALTER TABLE CHAT_MESSAGE ADD CONSTRAINT FK_CHAT_MESSAGE_TO_CHAT_ROOM_STAFF_ID FOREIGN KEY (
		STAFF_ID
)
REFERENCES STAFF (
		STAFF_ID
);

ALTER TABLE CHAT_MESSAGE ADD CONSTRAINT FK_CHAT_MESSAGE_TO_CHAT_ROOM_DEPT_IDEN FOREIGN KEY (
		DEPT_IDEN
)
REFERENCES department (
		DEPT_IDEN
);

ALTER TABLE STAFF ADD CONSTRAINT FK_STAFF_TO_position_POSITION_IDENTIFIED_CODE FOREIGN KEY (
		POSITION_IDENTIFIED_CODE
)
REFERENCES position (
		POSITION_IDENTIFIED_CODE
);

ALTER TABLE STAFF ADD CONSTRAINT FK_STAFF_TO_department_DEPT_IDEN FOREIGN KEY (
		DEPT_IDEN
)
REFERENCES department (
		DEPT_IDEN
);

ALTER TABLE STAFF ADD CONSTRAINT FK_STAFF_TO_LOG_RECORD_LOG_IDEN FOREIGN KEY (
		LOG_IDEN
)
REFERENCES LOG_RECORD (
		LOG_IDEN
);

ALTER TABLE ROOM ADD CONSTRAINT FK_ROOM_TO_BED_TYPE_BED_ID FOREIGN KEY (
		BED_ID
)
REFERENCES BED_TYPE (
		BED_ID
);

ALTER TABLE ROOM ADD CONSTRAINT FK_ROOM_TO_ROOM_TYPE_TYPE_ID FOREIGN KEY (
		TYPE_ID
)
REFERENCES ROOM_TYPE (
		TYPE_ID
);

ALTER TABLE ROOM ADD CONSTRAINT FK_ROOM_TO_VIEW_TYPE_VIEW_ID FOREIGN KEY (
		VIEW_ID
)
REFERENCES VIEW_TYPE (
		VIEW_ID
);

ALTER TABLE REP_MENU ADD CONSTRAINT FK_REP_MENU_TO_DINING_DINING_ID FOREIGN KEY (
		DINING_ID
)
REFERENCES DINING (
		DINING_ID
);

ALTER TABLE DINING_OPER_TIME ADD CONSTRAINT FK_DINING_OPER_TIME_TO_DINING_DINING_ID FOREIGN KEY (
		DINING_ID
)
REFERENCES DINING (
		DINING_ID
);

ALTER TABLE ROOM_FEATURE ADD CONSTRAINT FK_ROOM_FEATURE_TO_ROOM_ROOM_ID FOREIGN KEY (
		ROOM_ID
)
REFERENCES ROOM (
		ROOM_ID
);

ALTER TABLE DINING_RESERVATION ADD CONSTRAINT FK_DINING_RESERVATION_TO_DINING_DINING_ID FOREIGN KEY (
		DINING_ID
)
REFERENCES DINING (
		DINING_ID
);

ALTER TABLE DINING_RESERVATION ADD CONSTRAINT FK_DINING_RESERVATION_TO_MIMIR_USER_USER_NUM FOREIGN KEY (
		USER_NUM
)
REFERENCES MIMIR_USER (
		USER_NUM
);

ALTER TABLE DINING_RESERVATION ADD CONSTRAINT FK_DINING_RESERVATION_TO_PAYMENT_PAYMENT_ID FOREIGN KEY (
		PAYMENT_ID
)
REFERENCES PAYMENT (
		PAYMENT_ID
);

ALTER TABLE DINING_RESERVATION ADD CONSTRAINT FK_DINING_RESERVATION_TO_NON_MEMBER_NON_MEM_ID FOREIGN KEY (
		NON_MEM_ID
)
REFERENCES NON_MEMBER (
		NON_MEM_ID
);

ALTER TABLE staff_permission ADD CONSTRAINT FK_staff_permission_TO_permission_PERMISSION_ID_CODE FOREIGN KEY (
		PERMISSION_ID_CODE
)
REFERENCES permission (
		PERMISSION_ID_CODE
);

ALTER TABLE staff_permission ADD CONSTRAINT FK_staff_permission_TO_STAFF_STAFF_ID FOREIGN KEY (
		STAFF_ID
)
REFERENCES STAFF (
		STAFF_ID
);



ALTER TABLE CHAT_ROOM ADD CONSTRAINT FK_CHAT_ROOM_TO_MIMIR_USER_USER_NUM FOREIGN KEY (
		USER_NUM
)
REFERENCES MIMIR_USER (
		USER_NUM
);

ALTER TABLE CHAT_ROOM ADD CONSTRAINT FK_CHAT_ROOM_TO_STAFF_STAFF_ID FOREIGN KEY (
		STAFF_ID
)
REFERENCES STAFF (
		STAFF_ID
);

ALTER TABLE CHAT_ROOM ADD CONSTRAINT FK_CHAT_ROOM_TO_STAFF_DEPT_IDEN FOREIGN KEY (
		DEPT_IDEN
)
REFERENCES department (
		DEPT_IDEN
);
